// src/utils/boardLayout.js

const layout = [
    ['K3', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'K3', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'K3'],
    ['NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL'],
    ['NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL'],
    ['H2', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'H2'],
    ['NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL'],
    ['NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL'],
    ['NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL'],
    ['K3', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'CENTER', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'K3'],
    ['NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL'],
    ['NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL'],
    ['NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL'],
    ['H2', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'H2'],
    ['NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL', 'NORMAL'],
    ['NORMAL', 'K2', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'H3', 'NORMAL', 'NORMAL', 'NORMAL', 'K2', 'NORMAL'],
    ['K3', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'NORMAL', 'K3', 'NORMAL', 'NORMAL', 'NORMAL', 'H2', 'NORMAL', 'NORMAL', 'K3']
];

export default layout;
